### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by FoseFx** [bttv-android/bttv#81]
- [x] create said file
- [x] move "for contributors" section of readme there and re-write some of it
- [x] add PR and issue standards
